Repository apache/flink-connector-aws, pull requests merged in 2022-11, with the labels that each got.

#30 [hotfix][Connectors/AWS] Fix Flink configuration in CI build
  .github/workflows/ci.yml
Labels: component=BuildSystem

#29 [FLINK-29895] Further increase unit test coverage for DynamoDbSink
  flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSink.java
  flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSinkWriter.java
  flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/DynamoDbWriteRequest.java
  flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/client/DynamoDbAsyncClientProvider.java
  flink-connector-dynamodb/src/main/java/org/apache/flink/connector/dynamodb/sink/client/SdkClientProvider.java
  flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSinkTest.java
  flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbSinkWriterTest.java
  flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbWriteRequestTest.java
  flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/sink/DynamoDbWriterStateSerializerTest.java
  flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/table/RowDataElementConverterTest.java
  flink-connector-dynamodb/src/test/java/org/apache/flink/connector/dynamodb/util/DynamoDbSerializationUtilTest.java
Labels: component=Connectors/DynamoDB

#26 [FLINK-25859][Connectors/DynamoDB][docs] DynamoDB sink documentation
  .idea/vcs.xml
  docs/content.zh/docs/connectors/datastream/dynamodb.md
  docs/content.zh/docs/connectors/table/dynamodb.md
  docs/content/docs/connectors/datastream/dynamodb.md
  docs/content/docs/connectors/table/dynamodb.md
Labels: component=Documentation
