Repository apache/flink-connector-aws, pull requests merged in 2023-01, with the labels that each got.

#45 [FLINK-30633][Connectors/AWS] Update AWS SDKv2 to v2.19.14 and Netty to 4.1.86.Final for 3.x
  flink-sql-connector-dynamodb/src/main/resources/META-INF/NOTICE
  pom.xml
Labels: component=Connectors/DynamoDB

#36 [FLINK-30378][docs] Use modified sql_connector_download_table shortcode
  docs/data/dynamodb.yml
  docs/data/firehose.yml
  docs/data/kinesis.yml
Labels: component=Documentation

#48 [FLINK-30762][ci] Add nightly build workflow
  .github/workflows/common.yml
  .github/workflows/nightly.yml
  .github/workflows/push_pr.yml
  README.md
Labels: component=BuildSystem

#50 [FLINK-30783][Connectors/AWS] Add a pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: component=BuildSystem
